### PR TITLE
Navi

### PR DESCRIPTION
**Pull request by rlajous**
## Summary

- NAVI

### CODE REVIEW

**Review by SKOLZ — APPROVED** [review]

**Review by mpizzagalli — CHANGES_REQUESTED** [review]
Please pick better photos...

**Review by SKOLZ — CHANGES_REQUESTED** [review]
use a single photo instead of 2.

**Review by mcallegari10 — CHANGES_REQUESTED** [review]
Not really a fan of the operators being used

**Comment by rlajous** [comment]
Give me back acces to update the ascii art

**Pull request closed without merging**
