### PR TITLE
Auth service test

### PR DESCRIPTION
**Pull request by damfinkel**
## Summary

Tested AuthService and LocalStorageService

With this, we achieve >70% in both Statements and Lines, leaving only branches and functions below that number.

## Screenshots

image
image

### CODE REVIEW

**Comment by damfinkel** [comment]
I'm testing something, ignore this comment

**Comment by damfinkel** [comment]
I'm testing something, ignore this comment

**Review by damfinkel — COMMENTED** [review]
Trying out something, ignore this review

**Review by damfinkel — COMMENTED** [review]
Something new

**Review by pabloferro — APPROVED** [review]
Looks good.

My suggestion for routes tests was to have them in each screen so you would have:

`screens/Registration/index.test.tsx`
```ts
describe('when there is a user', () => {
  const userState = { user: { id: 1, sessionToken: 'token' } };

  test('redirects to Home screen when being on the registration path', async () => {
    window.history.pushState({}, '', PATHS.registration);
    render(<WrappedRoutes userState={userState} />);
    await waitFor(() => expect(screen.getByText('You are logged in.')).toBeInTheDocument());
  });
});

describe('when there is no user', () => {
  const userState = { user: null };
  test('shows Registration screen when being on the registration path', async () => {
    window.history.pushState({}, '', PATHS.registration);
    render(<WrappedRoutes userState={userState} />);
    await waitFor(() => expect(screen.getByText('Registration:registration')).toBeInTheDocument());
  });
});
```
And so on on each screen.

**Pull request merged**
